name: openai_dalle_wrapper
description: OpenAI Dall*E Wrapper 
version: 0.0.1
homepage: https://github.com/themmfa/openai_dalle_wrapper

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_lints: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  